framework:
    assets:
        packages:
            zetaMedsTheme:
                json_manifest_path: '%kernel.project_dir%/public/zetameds-theme/manifest.json' 
            # bootstrapTheme:
            #     json_manifest_path: '%kernel.project_dir%/public/bootstrap-theme/manifest.json' 
