brille24_tierprice_bundle:
    resource: '@Brille24SyliusTierPricePlugin/Resources/config/routing.yml'

app.page.terms_and_conditions:
    path: /en_US/terms-and-conditions
    controller: App\Controller\PageController::termsAndConditions
    methods: GET

app.page.about_us:
    path: /en_US/about-us
    controller: App\Controller\PageController::aboutUs
    methods: GET

app.page.contact_us:
    path: /en_US/send-contact-request
    controller: App\Controller\PageController::contactUs
    methods: POST

app.page.faq:
    path: /en_US/faq
    controller: App\Controller\PageController::faq
    methods: GET

app.page.add_health_inf:
    path: /en_US/add-health-info/{count}
    controller: App\Controller\PageController::addHealthInfo
    methods: GET
